name: PR Build

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        working-directory: ${{ github.workspace }}
        run: dotnet restore rbnswartz.LinuxIntegration.sln

      - name: Build
        working-directory: ${{ github.workspace }}
        run: dotnet build rbnswartz.LinuxIntegration.sln --configuration Release --no-restore
